import { Doctor } from "@/types/doctor";

export const sampleDoctors: Doctor[] = [
  {
    id: '1',
    name: 'Dr. John Smith',
    image: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?q=80&w=2070&auto=format&fit=crop",
    qualification: 'MBBS, MD',
    specialization: 'General Medicine',
    experience: '10+ years',
    rating: 4.8,
    videoConsultation: true,
    videoConsultationFee: 800,
    consultationFee: 500,
    availability: {
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      timeSlots: ['09:00 AM', '10:00 AM', '11:00 AM', '02:00 PM', '03:00 PM', '04:00 PM'],
    },
    location: 'Apollo Hospital, Bangalore',
    languages: ['English', 'Hindi', 'Kannada'],
    about: 'Dr. John Smith is a highly experienced general physician with over 10 years of practice.',
  },
  {
    id: '2',
    name: 'Dr. Divya Renuka',
    image: "",
    qualification: 'MBBS, MS',
    specialization: 'Gynecologist',
    experience: '8+ years',
    rating: 4.9,
    videoConsultation: true,
    videoConsultationFee: 1000,
    consultationFee: 800,
    availability: {
      days: ['Monday', 'Wednesday', 'Friday'],
      timeSlots: ['10:00 AM', '11:00 AM', '12:00 PM', '04:00 PM', '05:00 PM'],
    },
    location: 'Manipal Hospital, Bangalore',
    languages: ['English', 'Hindi', 'Telugu'],
    about: 'Dr. Divya Renuka is a dedicated gynecologist with expertise in women\'s health.',
  },
  {
    id: '3',
    name: 'Dr. Rajesh Kumar',
    image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?q=80&w=2070&auto=format&fit=crop",
    qualification: 'MBBS, DNB',
    specialization: 'Pediatrician',
    experience: '12+ years',
    rating: 4.7,
    videoConsultation: false,
    videoConsultationFee: null,
    consultationFee: 600,
    availability: {
      days: ['Tuesday', 'Thursday', 'Saturday'],
      timeSlots: ['09:00 AM', '10:00 AM', '11:00 AM', '03:00 PM', '04:00 PM'],
    },
    location: 'Rainbow Children\'s Hospital, Bangalore',
    languages: ['English', 'Hindi', 'Kannada'],
    about: 'Dr. Rajesh Kumar is a skilled pediatrician with extensive experience in child healthcare.',
  },
];