// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdfnlocveyixjtanenhj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kZm5sb2N2ZXlpeGp0YW5lbmhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYwMDk0NjEsImV4cCI6MjA1MTU4NTQ2MX0.CMqA5R22OjcOXUkQX4LJXpOwFLiFB9eM5Dv6UZkpqN0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);