// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irklxyohnsadmayldvrq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlya2x4eW9obnNhZG1heWxkdnJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU4NzY3ODcsImV4cCI6MjA1MTQ1Mjc4N30.9sLDEBdib3mPEyhXp80KQ-TQfiBaexqM9La4UM1kf0A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);